apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-apps
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 7
      maxUnavailable: 2
  selector:
    matchLabels:
      app: nodejs-apps
  template:
    metadata:
      labels:
        app: nodejs-apps
    spec:
      containers:
        - name: app
          image: 861458561402.dkr.ecr.us-east-2.amazonaws.com/nodejs-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always
      
